### PR TITLE
Improve key implementation

### PR DESCRIPTION
**Pull request by p-x9**
Within a Protocol Extension, stored property could not be defined, and an error occurred in the definition of the AssociatedObject's Key.

Therefore, I modified the implementation of Key to use Selector.

related to: https://github.com/p-x9/AssociatedObject/pull/24

### CODE REVIEW

**Comment by mlch911** [comment]
We can add a assert in the setter to check is there anything wrong.
```swift
var string: String? {
    get {
        objc_getAssociatedObject(
            self,
            Self.__associated_stringKey
        ) as? String?
        ?? nil
    }
    set {
        objc_setAssociatedObject(
            self,
            Self.__associated_stringKey,
            newValue,
            .OBJC_ASSOCIATION_ASSIGN
        )
        assert(string == newValue)    // <-- Add this.
    }
}

static var __associated_stringKey: UnsafeRawPointer {
    unsafeBitCast(
        NSSelectorFromString("__macro_local_6stringfMu_"),
        to: UnsafeRawPointer.self
    )
}
```

**Comment by p-x9** [comment]
@mlch911 

I think it is a good idea.
However, I think it would be difficult to check that the type is Equatable conforming using only syntax.

**Comment by mlch911** [comment]
Maybe this.
```swift
set {
        objc_setAssociatedObject(
            self,
            Self.__associated_stringKey,
            newValue,
            .OBJC_ASSOCIATION_ASSIGN
        )
    if type.of(string).confirm(to: Equitable.self) {
        assert(string == newValue)
    }
}
```

**Comment by p-x9** [comment]
@mlch911 This function may exist only in NSObject.

**Comment by p-x9** [comment]
I have made some changes to the way keys are generated in order to support future platforms, such as Linux, where the Objective-C runtime is not available.

Instead of using Selector, function pointers are used as keys.

**Comment by mlch911** [comment]
> I have made some changes to the way keys are generated in order to support future platforms, such as Linux, where the Objective-C runtime is not available.
> 
> Instead of using Selector, function pointers are used as keys.
> 
> ```swift
> static var __associated_boolKey: UnsafeRawPointer {
>     let f: @convention(c) () -> Void = {}
>     return unsafeBitCast(f, to: UnsafeRawPointer.self)
> }
> ```

Would this return the same pointer every time? Shouldn't this be like this?
```swift
static let __associated_boolKey: UnsafeRawPointer = {
    let f: @convention(c) () -> Void = {}
    return unsafeBitCast(f, to: UnsafeRawPointer.self)
}()
```

**Comment by p-x9** [comment]
Closure functions are not defined dynamically, but statically, just like any other function definition.
Therefore, it should return the same pointer value change each time.

**Pull request merged**
