### PR TITLE
Add Support for Basic Type Detection

### PR DESCRIPTION
**Pull request by mlch911**
Add Support for Basic Type Detection.

You can now write code like this without type annotation.
```swift
@AssociatedObject(.OBJC_ASSOCIATION_ASSIGN)
var int = 10

@AssociatedObject(.OBJC_ASSOCIATION_ASSIGN)
var boolArray = [true, false]

@AssociatedObject(.OBJC_ASSOCIATION_ASSIGN)
var optionalIntArray = [1, 2, 3, nil]

@AssociatedObject(.OBJC_ASSOCIATION_ASSIGN)
var dic = ["t": "a", "s": "b"]
```

### CODE REVIEW

**Comment by p-x9** [comment]
Thank you. 
I think it is a great idea and implementation.

I will read the code in more detail when I have more time.

**Comment by p-x9** [comment]
@mlch911 
I have read and tested the code and it was great.

One issue was related to the handling of arrays, as follows.

```swift
var doubleArray = [1, 2.0, 3.0]
```

In this case, there is a mix of Int and Double literals, but it should actually be treated as an array of Doubles.

The solution to this issue may be tedious, so if you want, I can continue to work on it.

**Comment by mlch911** [comment]
> @mlch911 I have read and tested the code and it was great.
> 
> One issue was related to the handling of arrays, as follows.
> 
> ```swift
> var doubleArray = [1, 2.0, 3.0]
> ```
> 
> In this case, there is a mix of Int and Double literals, but it should actually be treated as an array of Doubles.
> 
> The solution to this issue may be tedious, so if you want, I can continue to work on it.

Yes, please.

**Comment by p-x9** [comment]
@mlch911 

Hi, I have made some improvements based on your implementation.
What do you think?

**Comment by mlch911** [comment]
It's great. I think it's ready to merge.

**Pull request merged**
