### PR TITLE
Fix Typo

### PR DESCRIPTION
**Pull request by mlch911**

### CODE REVIEW

**Comment by p-x9** [comment]
Thanks. @mlch911 
I think I may need to modify the macro implementation as well to avoid generating unnecessary spaces.

I will take a look at it later.

**Comment by p-x9** [comment]
@mlch911 
Could you try changing the `type` to `type.trimmed` in the following two places?
This is to remove the whitespace specified for `trailingTrivia`.

https://github.com/p-x9/AssociatedObject/blob/ac2684bf9e1d5438b8a72f45f03ed671b75176e0/Sources/AssociatedObjectPlugin/AssociatedObjectMacro.swift#L228-L230

https://github.com/p-x9/AssociatedObject/blob/ac2684bf9e1d5438b8a72f45f03ed671b75176e0/Sources/AssociatedObjectPlugin/AssociatedObjectMacro.swift#L286-L288

**Comment by mlch911** [comment]
done

**Comment by mlch911** [comment]
done

**Comment by p-x9** [comment]
Thanks

**Pull request merged**
